services:
  postgres:
    container_name: pruebasportal
    hostname: portalAutoatencion
    image: postgres
    volumes:
      - C:/postgres:/var/lib/postgresql/data
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres