services:
  - type: web
    name: portal-autoatencion
    env: python
    runtime: python-3.11.9
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn portalAutoatencion.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        fromDatabase:
          name: portal-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: portal-autoatencion.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://portal-autoatencion.onrender.com
      - key: DB_NAME
        fromDatabase:
          name: portal-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: portal-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: portal-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: portal-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: portal-db
          property: port

databases:
  - name: portal-db
    databaseName: portal
    user: portal_user
    plan: free

